import "./gameplay/system"
import "./gameplay/shield"
import "./gameplay/itemSystem"
import "./gameplay/itemDamages"
import "./gameplay/hud"
import "./gameplay/foods"
import "./gameplay/config"

import "./offhand/foodswap"
import "./offhand/offhand"

import "./misc/entity_cramming"
import "./misc/netherite_wind_charges"
import "./misc/totem"
import "./misc/bow_ding"
import "./misc/dolphins_grace"
import "./misc/xp"
import "./misc/waterlog"
import "./misc/portal_waterlog"
import "./misc/tnt_minecart"
import "./misc/armorhealing"

import "./reworks/string_duper_rework"
import "./alpha/combat_log"
import "./alpha/antidupe"
import "./alpha/autosort"
import "./alpha/invis_death"
import "./alpha/stackrefill"
import "./alpha/pickuplock"